apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: jwt-opa
  namespace: gloo-system
spec:
  configs:
    - opa_auth:
        modules:
          - name: allow-jwt
            namespace: gloo-system
        query: "data.test.allow == true"