apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: foxtrot
  namespace: gloo-system
spec:
  kube:
    selector:
      app: foxtrot
    serviceName: foxtrot
    serviceNamespace: foxtrot
    servicePort: 80
    subsetSpec:
      selectors:
        - keys:
            - version
